### ISSUE TITLE
WOA Deployer GUI has stoped working.

### ISSUE THREAD

**Issue by Dr-InSide** [SuperJMN/Deployer#12]
My equipment: 
- Last Depolyer from the Store
- Windows 10 x64 19045.3448 [German]
- .NET Runtime 6.0.22

I tried it on several computers, Deployer crashes immediately after startup with the error message "WOA Deployer GUI has stopped working.".

The error has been going on for months, it would be nice if a solution could finally be found for this.

Thanks a lot!!

**Comment by SuperJMN** [comment]
OK, the solution is here. Sorry for the late reply, but I don't think much people is using this nowadays. If only there were more people supporting it, I would dedicate more time to it.

By the way, the fixed version won't be available in the Microsoft Windows Store, but in the [Releases](https://github.com/SuperJMN/Deployer/releases) section. Please, check it. 

Thanks for your interest.
